name: "Pull Request Checks"
on: pull_request
jobs:
  # Enforces the update of a changelog file on every pull request 
  check-changelog-change:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dangoslen/changelog-enforcer@v2
      with:
        versionPattern: '### (Version \\d+\\.\\d+\\.\\d* - \\d{4}-\\d{2}-\\d{2}|Upcoming version)'
