name: "Pull Request Checks"
on: pull_request
jobs:
  # Enforce the update of the changelog file
  check-changelog-change:
    runs-on: ubuntu-latest
    steps:
    - uses: dangoslen/changelog-enforcer@v3
  # Ensure markdown files are formatted consistently
  lint-markdown-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xt0rted/markdownlint-problem-matcher@v2
      - run: npm install -g markdownlint-cli
      - run: markdownlint '**/*.md'
